// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     TSTypesJenny
//     LatestMajorsOrXJenny
//
// Run 'make gen-cue' from repository root to regenerate.

export interface QueryHistoryPreference {
  /**
   * one of: '' | 'query' | 'starred';
   */
  homeTab?: string;
}

export interface EnabledQueryTypes {
  applyForAdmin?: boolean;
  enabledTypes?: Array<string>;
}

export const defaultEnabledQueryTypes: Partial<EnabledQueryTypes> = {
  enabledTypes: [],
};

export interface Preferences {
  /**
   * Toggle to set available query types for the tenant
   */
  enabledQueryTypes?: EnabledQueryTypes;
  /**
   * UID for the home dashboard
   */
  homeDashboardUID?: string;
  /**
   * Selected language (beta)
   */
  language?: string;
  /**
   * Explore query history preferences
   */
  queryHistory?: QueryHistoryPreference;
  /**
   * light, dark, empty is default
   */
  theme?: string;
  /**
   * Format for dashboards, panels and reports timestamps
   */
  timeFormat?: string;
  /**
   * The timezone selection
   * TODO: this should use the timezone defined in common
   */
  timezone?: string;
  /**
   * day of the week (sunday, monday, etc)
   */
  weekStart?: string;
}
